title: Math for ML Notes
author: n03an
logo: logo_n.png

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: "off"

sphinx:
  config:
    mathjax_path: https://cdn.jsdelivr.net/npm/mathjax@3.2/es5/tex-mml-chtml.js
    mathjax3_config:
      "HTML-CSS": { preferredFont: "STIX", matchFontHeight: true, scale: 130 }

parse:
  myst_enable_extensions:
    # don't forget to list any other extensions you want enabled,
    # including those that are enabled by default!
    - amsmath
    - dollarmath
    - attrs_inline
    - smartquotes
    - html_image

# Information about where the book exists on the web
repository:
  url: https://github.com/N0-man/math-for-machine-learning # Online location of your book
  branch: main # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true
